"""Pydantic models for the compliance domain.

These models support BSA/AML transaction monitoring, CTR/SAR filing workflows,
structuring detection, and customer risk scoring as required by Trebanx's
62-document BSA/AML compliance framework.
"""

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class AlertType(StrEnum):
    CTR_THRESHOLD = "ctr_threshold"
    STRUCTURING = "structuring"
    SUSPICIOUS_ACTIVITY = "suspicious_activity"
    OFAC_MATCH = "ofac_match"
    EDD_TRIGGER = "edd_trigger"
    VELOCITY_ANOMALY = "velocity_anomaly"


class AlertPriority(StrEnum):
    ROUTINE = "routine"
    ELEVATED = "elevated"
    URGENT = "urgent"
    CRITICAL = "critical"


class RecommendedAction(StrEnum):
    FILE_CTR = "file_ctr"
    FILE_SAR = "file_sar"
    ESCALATE_TO_BSA_OFFICER = "escalate_to_bsa_officer"
    ENHANCED_MONITORING = "enhanced_monitoring"
    BLOCK_TRANSACTION = "block_transaction"


class AlertStatus(StrEnum):
    NEW = "new"
    UNDER_REVIEW = "under_review"
    FILED = "filed"
    DISMISSED_WITH_RATIONALE = "dismissed_with_rationale"
    ESCALATED = "escalated"


class CaseStatus(StrEnum):
    OPEN = "open"
    INVESTIGATING = "investigating"
    PENDING_FILING = "pending_filing"
    FILED = "filed"
    CLOSED = "closed"


class RiskLevel(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    PROHIBITED = "prohibited"


class StructuringTypology(StrEnum):
    MICRO = "micro"
    SLOW = "slow"
    FAN_OUT = "fan_out"
    FUNNEL = "funnel"


class SARDraftStatus(StrEnum):
    DRAFT = "draft"
    REVIEWED = "reviewed"
    APPROVED = "approved"
    FILED = "filed"
    REJECTED = "rejected"


# ---------------------------------------------------------------------------
# Transaction representation used by compliance monitoring
# ---------------------------------------------------------------------------


class ComplianceTransaction(BaseModel):
    """Minimal transaction representation consumed by compliance rules."""

    transaction_id: str
    user_id: str
    amount: float
    currency: str = "USD"
    transaction_type: str = ""  # e.g. circle_contribution, remittance_send, etc.
    recipient_id: str | None = None
    sender_id: str | None = None
    geo_country: str | None = None
    circle_id: str | None = None
    initiated_at: datetime


# ---------------------------------------------------------------------------
# Core compliance models
# ---------------------------------------------------------------------------


class ComplianceAlert(BaseModel):
    """A single compliance alert generated by monitoring rules."""

    alert_id: str
    alert_type: AlertType
    user_id: str
    transaction_ids: list[str] = Field(default_factory=list)
    amount_total: float = 0.0
    description: str = ""
    regulatory_basis: str = ""
    recommended_action: RecommendedAction
    priority: AlertPriority
    status: AlertStatus = AlertStatus.NEW
    created_at: datetime
    reviewed_at: datetime | None = None
    reviewed_by: str | None = None
    resolution_notes: str | None = None


class ComplianceCase(BaseModel):
    """Groups related alerts into an investigation case."""

    case_id: str
    user_id: str
    alert_ids: list[str] = Field(default_factory=list)
    case_type: str = ""
    status: CaseStatus = CaseStatus.OPEN
    assigned_to: str | None = None
    opened_at: datetime
    closed_at: datetime | None = None
    filing_reference: str | None = None
    narrative: str | None = None


class CustomerRiskProfile(BaseModel):
    """Dynamic risk profile for a customer."""

    user_id: str
    risk_level: RiskLevel = RiskLevel.LOW
    risk_score: float = Field(ge=0.0, le=1.0, default=0.0)
    risk_factors: list[str] = Field(default_factory=list)
    edd_required: bool = False
    last_reviewed: datetime | None = None
    next_review_due: datetime | None = None
    review_frequency_days: int = 365


# ---------------------------------------------------------------------------
# CTR-specific models
# ---------------------------------------------------------------------------


class CTRDailyTotal(BaseModel):
    """Running daily cumulative total for a user."""

    user_id: str
    business_date: str  # YYYY-MM-DD in user's local timezone
    cumulative_amount: float = 0.0
    transaction_ids: list[str] = Field(default_factory=list)
    transaction_details: list[dict] = Field(default_factory=list)
    threshold_met: bool = False
    alert_generated: bool = False


class CTRFilingPackage(BaseModel):
    """Data package assembled for CTR filing."""

    package_id: str
    user_id: str
    business_date: str
    total_amount: float
    transaction_count: int
    transaction_details: list[dict] = Field(default_factory=list)
    customer_info: dict = Field(default_factory=dict)
    institution_info: dict = Field(
        default_factory=lambda: {
            "name": "Trebanx",
            "type": "Money Services Business",
            "identifier": "TREBANX-MSB",
        }
    )
    filing_metadata: dict = Field(default_factory=dict)
    status: str = "pending"  # pending / filed / rejected
    assembled_at: datetime
    filed_at: datetime | None = None
    filing_reference: str | None = None


# ---------------------------------------------------------------------------
# Structuring detection models
# ---------------------------------------------------------------------------


class StructuringDetection(BaseModel):
    """Result of structuring pattern analysis."""

    detection_id: str
    user_id: str
    typology: StructuringTypology
    confidence: float = Field(ge=0.0, le=1.0)
    transaction_ids: list[str] = Field(default_factory=list)
    amount_total: float = 0.0
    description: str = ""
    indicators: dict = Field(default_factory=dict)
    detected_at: datetime


# ---------------------------------------------------------------------------
# SAR draft models
# ---------------------------------------------------------------------------


class SARDraft(BaseModel):
    """Machine-generated SAR narrative draft requiring human review."""

    draft_id: str
    case_id: str
    user_id: str
    narrative: str = ""
    sections: dict = Field(default_factory=dict)
    confidence_note: str = ""
    status: SARDraftStatus = SARDraftStatus.DRAFT
    generated_at: datetime
    reviewed_at: datetime | None = None
    reviewed_by: str | None = None
    machine_generated_disclaimer: str = (
        "MACHINE-GENERATED DRAFT — This narrative was automatically generated "
        "by Lakay Intelligence and MUST be reviewed and approved by a qualified "
        "BSA/AML compliance officer before filing. Do not file without human review."
    )


# ---------------------------------------------------------------------------
# Risk scoring models
# ---------------------------------------------------------------------------


class RiskFactorDetail(BaseModel):
    """A single contributing factor to the customer risk score."""

    factor_name: str
    category: str  # transaction / geographic / behavioral / circle
    weight: float = 0.0
    score: float = Field(ge=0.0, le=1.0, default=0.0)
    description: str = ""


class CustomerRiskAssessment(BaseModel):
    """Full risk assessment output for a customer."""

    user_id: str
    risk_score: float = Field(ge=0.0, le=1.0)
    risk_level: RiskLevel
    factor_details: list[RiskFactorDetail] = Field(default_factory=list)
    edd_required: bool = False
    review_frequency_days: int = 365
    previous_risk_level: RiskLevel | None = None
    level_changed: bool = False
    assessed_at: datetime


class RiskScoreHistory(BaseModel):
    """Historical risk score record for audit trail."""

    user_id: str
    risk_score: float
    risk_level: RiskLevel
    trigger_event: str = ""
    assessed_at: datetime


# ---------------------------------------------------------------------------
# API request/response models
# ---------------------------------------------------------------------------


class ComplianceRiskRequest(BaseModel):
    user_id: str


class ComplianceRiskResponse(BaseModel):
    user_id: str
    risk_level: RiskLevel = RiskLevel.LOW
    risk_score: float = Field(ge=0, le=100)
    factors: dict = Field(default_factory=dict)
    model_version: str = "compliance-v1"
    computed_at: datetime
